Controllers/AdminController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using CuatroCaminosMvcApplication.Models;

namespace CuatroCaminosMvcApplication.Controllers
{
    [Authorize(Users = "admin")]
    public class AdminController : Controller
    {

        DataManager dataManager = new DataManager();

        //
        // GET: /Admin/

        public ActionResult Index()
        {
//            DownloadCSV();

            return View(dataManager.GetAdministrator());
        }

        //
        // GET: /Admin/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Admin/Create

        [CookieFilter]
        public ActionResult Create()
        {

            SetViewBag();

            return View();
        } 

        //
        // POST: /Admin/Create

        [CookieFilter]
        [HttpPost]
        public ActionResult Create(Administrators administrators)
        {

            dataManager.CreateAdministrators(administrators);
            
            
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Admin/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Admin/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Admin/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View(dataManager.GetAdministrator(id));
        }

        //
        // POST: /Admin/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                dataManager.DeleteAdministrator(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void SetViewBag()
        {
            ViewBag.month = dataManager.SelectListСписокМесяцев(FromFormData.month);
            ViewBag.Название_танца = dataManager.SelectListСписокНаправленийТанцев(FromFormData.Название_танца);
            ViewBag.Код_Ученика = dataManager.SelectListСписокФиоОтОплаты(FromFormData.Код_Ученика, null);
        }


//        private void ExportAsCSV(IEnumerable<Списки_людей> filterRecords)
 
        private void ExportAsCSV()
         {
            Cuatro_Caminos_BDEntities bd = new Cuatro_Caminos_BDEntities();

            var sw = new StringWriter();
         
            //write the header 
            sw.WriteLine(String.Format("{0},{1},{2},{3}", 1, 2, 2, 4));

            //write every subscriber to the file 
//            var resourceManager = new ResourceManager(typeof(CMSMessages));
            foreach (Списки_людей record in bd.Списки_людей)
            {
                sw.WriteLine(String.Format("{0},{1},{2},{3}", "тест", record.ФИО, record.Телефон, record.Пол));
            }

            Response.Clear();
            Response.AddHeader("Content-Disposition", "attachment; filename=adressenbestand.csv");
            Response.ContentType = "text/csv";
            Response.Write(sw);
            Response.End();

        }


        public ActionResult EportGroupFileCsv()
        {
            ICollection<Оплата> оплата = dataManager.GetОплата();
//             оплата.Select(e => new {e.Названия_танцев.Код, e.Названия_танцев.Название_танца});
            

            return View();
        }


 
    }



}

Controllers/CashController.cs
using System;
using System.Collections.Generic;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuatroCaminosMvcApplication.Models;

namespace CuatroCaminosMvcApplication.Controllers
{
    [Authorize(Users = "admin")]
    public class CashController : Controller
    {
        //
        // GET: /Cash/

        DataManager dataManager = new DataManager();

        public ActionResult Index()
        {

            return View();
        }

        public PartialViewResult IndexPartial()
        {
            return PartialView("IndexPartial",dataManager.GetCash());
        }


        //
        // GET: /Cash/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Cash/Create

        public ActionResult Create()
        {

            SetViewBag();
            ViewBag.DataTimeCreate = DateTime.Now;

            return View();
        } 

        //
        // POST: /Cash/Create

        [HttpPost]
        public ActionResult Create(Cash cash, FormCollection collection)
        {

            try
            {
                // TODO: Add insert logic here

                dataManager.CreateCash(cash);

                return RedirectToAction("IndexPartial");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Cash/Edit/5

        public ActionResult Edit(int id)
        {
            Cash cash = dataManager.GetCash(id);

            FromFormData.Дата_оплаты=cash.DataTimePay;
            FromFormData.Код_Ученика = cash.PeopleId;
            FromFormData.Название_танца = cash.GroupId;

            SetViewBag();

            ViewBag.DataPay = cash.DataTimePay;

            return View(cash);
        }

        //
        // POST: /Cash/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                Cash cash = dataManager.GetCash(id);

                cash.DataTimeCreate = DateTime.Now;
                cash.LoginRecId = dataManager.LiginRecId();
                cash.Payment_expenses = true;
                cash.CategoryId = 1;

                UpdateModel(cash);

                dataManager.SaveChanges();

                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Cash/Delete/5
 
        public ActionResult Delete(int id)
        {

            return View();
        }

        //
        // POST: /Cash/Delete/5

        [HttpPost]
        public PartialViewResult Delete(int id, FormCollection collection)
        {



            try
            {
                // TODO: Add delete logic here

                dataManager.DeleteCash(id);

                return PartialView("IndexPartial", dataManager.GetCash());
            }
            catch
            {
                return PartialView("IndexPartial", dataManager.GetCash());
            }
        }


        public ActionResult CashAndPay()
        {
            CashAndPayViewModel cashAndPayViewModel = new CashAndPayViewModel(dataManager.GetCashAndPay());

            return View(cashAndPayViewModel);
        }

        private void SetViewBag()
        {
            ViewBag.Group = dataManager.SelectListСписокНаправленийТанцев(FromFormData.Название_танца);
            ViewBag.People = dataManager.SelectListСписокФио(FromFormData.Код_Ученика);
            ViewBag.Преподаватель = dataManager.SelectListИменаПреподавателей(FromFormData.Преподаватель);
        }


    }
}

Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI;
using CuatroCaminosMvcApplication.Models;


namespace CuatroCaminosMvcApplication.Controllers
{

    [Authorize]
    //    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class PeopleController : Controller
    {
        //
        // GET: /СпискиЛюдей/

        private Cuatro_Caminos_BDEntities db = new Cuatro_Caminos_BDEntities();

        //        private string[] alfavit = new string[] { "А", "Б", "В", "Г", "Д", "Е", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" };

        DataManager dataManager = new DataManager();

        public ActionResult Index(FormCollection collection, int? page, char? alfavit)
        {

            //            dataManager.GetPeaple();
            //int pageSize = 3;
            //int pageIndex = (page ?? 1) - 1; 

            ViewBag.Alfavit = dataManager.GetAlfavitFromФИО();


            return View(dataManager.GetPeaple(alfavit));
        }


        public ActionResult Group(int? group)
        {

            ViewBag.Название_танцев = dataManager.GetНазваниеТанцев();
            ViewBag.Имя_группы = dataManager.GetNameGroupFromId(group);
            Названия_танцев singleOrDefault = dataManager.GetНазваниеТанцев().SingleOrDefault(i => i.Код == @group);
            if (singleOrDefault != null)
                ViewBag.Description = singleOrDefault.Description;


            return View(dataManager.GetСписокФиоFromGroup(group));
        }


        public ActionResult Schools(int schools)
        {

            ICollection<Списки_людей> спискиЛюдей = dataManager.GetPeapleSchools(schools);
            Название_школ названиеШколы = dataManager.GetНазваниеШкол(schools);

            string названиеШкол = null;

            if (названиеШколы != null)
            {
                названиеШкол = названиеШколы.Школы;
            }

            ViewBag.School = String.Format(" '{0}' ", названиеШкол);

            ViewBag.Schools = dataManager.GetНазваниеШкол();


            return View(спискиЛюдей);
        }


        public ActionResult DoNotGo(int? group, int? day)
        {

            IDictionary<int, string> days = new Dictionary<int, string>();
            //            days.Add(-7, "1 неделю");
            //            days.Add(-14, "2 недели");
            //            days.Add(-21, "3 недели");
            days.Add(-30, "1 месяц");
            //            days.Add(-45, "1,5 месяца");
            days.Add(-60, "2 месяца");
            days.Add(-90, "3 месяца");

            ViewBag.Название_танцев = dataManager.GetНазваниеТанцев();
            ViewBag.Имя_группы = dataManager.GetNameGroupFromId(group);
            ViewBag.Days = days;

            return View(dataManager.GetPeapleDoNotGo(group, day));
        }




        //
        // GET: /СпискиЛюдей/Details/5

        public ActionResult Details(int id)
        {

            //            ViewData["Оплата"] = dataManager.GetОплатаFromФИО(id);
            int LoginRecId = dataManager.ListСписокВсехФио().Where(e => e.Код==id).Select(e=>e.LoginRecId).SingleOrDefault();
            Списки_людей спискиЛюдей = dataManager.GetPeapleFioFromId(LoginRecId);
            ViewBag.LoginRecFio = спискиЛюдей.ФИО;



            return View(dataManager.GetPeaple(id));
        }



        //
        // GET: /СпискиЛюдей/Create

        public ActionResult Create()
        {
            SetViewBag();
            ViewBag._Школы = dataManager.SelectListСписокВсехШкол(7);
            ViewBag._Название_SMS = dataManager.SelectListSms(1);

            return View();
        }

        //
        // POST: /СпискиЛюдей/Create

        [HttpPost]
        public ActionResult Create(Списки_людей спискиЛюдей, FormCollection collection)
        {

            //               ViewBag._Message = String.Format("Записись сохранена");

            // TODO: Add insert logic here


            dataManager.CreateНовыйКлиент(спискиЛюдей);
            return RedirectToAction("Index");


            //if (ModelState.IsValid)
            //{
            //    dataManager.CreateНовыйКлиент(спискиЛюдей);
            //    return RedirectToAction("Index");
            //}
            //else
            //{
            //    SetViewBag();
            //    return View();
            //}


        }

        //
        // GET: /СпискиЛюдей/Edit/5

        public ActionResult Edit(int id)
        {
            Списки_людей спискиЛюдей = dataManager.GetPeaple(id);


            SetViewBag(спискиЛюдей);

            return View(спискиЛюдей);
        }

        //
        // POST: /СпискиЛюдей/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {



            try
            {
                // TODO: Add update logic here

                if (ModelState.IsValid)
                {
                    Списки_людей спискиЛюдей = dataManager.GetPeaple(id);

                    спискиЛюдей.DateTimeRec = DateTime.Now;
                    спискиЛюдей.LoginRecId = dataManager.GetFromLoginToId(HttpContext.User.Identity.Name);

                    //if (collection["Выбыл_из_школы"] != "false")
                    //{
                    //    if (спискиЛюдей.Дата_выбытия == null)
                    //    {
                    //        спискиЛюдей.Дата_выбытия = DateTime.Now;
                    //    }

                    //}
                    //else
                    //{
                    //    спискиЛюдей.Дата_выбытия = null;
                    //}


                    UpdateModel(спискиЛюдей);
                    dataManager.SaveChanges();



                    ViewBag._Message = String.Format("Записись сохранена");

                    return RedirectToAction("Index");


                }
                else
                {
                    return View();
                }

            }
            catch
            {
                return View();
            }

        }

        //
        // GET: /СпискиЛюдей/Delete/5

        public ActionResult Delete(int id)
        {

            return View(dataManager.GetPeaple(id));
        }

        //
        // POST: /СпискиЛюдей/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                dataManager.DeletePeople(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Notphones()
        {
            return View(dataManager.NotPhonePeaple());
        }


        private void SetViewBag()
        {
            ViewBag._Название_SMS = dataManager.SelectListSms();
            ViewBag._Школы = dataManager.SelectListСписокВсехШкол();
            ViewBag._Пол = dataManager.SelectListStringSex();
            ViewBag._Вконтекте = dataManager.SelectListBool();
            ViewBag._Участие_в_выступлениях = dataManager.SelectListBool();

            ViewBag._Район = dataManager.SelectListСписокРайонов();
        }


        private void SetViewBag(Списки_людей спискиЛюдей)
        {
            ViewBag._Название_SMS = dataManager.SelectListSms(спискиЛюдей.Название_SMS.Код);
            ViewBag._Школы = dataManager.SelectListСписокВсехШкол(спискиЛюдей.Название_школ.Код);
            ViewBag._Пол = dataManager.SelectListStringSex(спискиЛюдей.Пол);
            ViewBag._Вконтекте = dataManager.SelectListBool(спискиЛюдей.Вконтекте);
            ViewBag._Участие_в_выступлениях = dataManager.SelectListBool(спискиЛюдей.Участие_в_выступлениях);

            ViewBag._Район = dataManager.SelectListСписокРайонов(спискиЛюдей.Район);
            ViewBag.Alfavit = dataManager.GetAlfavitFromФИО();

        }




        [HttpPost]
        public ActionResult PhoneExist(string Телефон, int? Код)
        {

            //            bool l = Код == null ? dataManager.IsPhoneExists(Телефон) : dataManager.IsPhoneExists(Телефон, Код);

            //if (Код == null)
            //{
            //            return Json(!dataManager.IsPhoneExists(Телефон), JsonRequestBehavior.AllowGet);
            //}
            //else
            //{

            List<string> str = dataManager.IsPhoneExists(Телефон, Код);

            if (str.Count == 0)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                string s1 = "";

                foreach (string s in str)
                {
                    s1 = s + ", " + s1;
                }
                return Json(String.Format("Такой номер телефона уже есть у: {0}. ", s1), JsonRequestBehavior.AllowGet);
            }

            //            }

            //            return Json(str, JsonRequestBehavior.AllowGet);

        }



        [HttpPost]
        public ActionResult EmailExist(string e_mail, int? Код)
        {
            bool l = Код == null ? dataManager.IsEmailExist(e_mail) : dataManager.IsEmailExist(e_mail, Код);

            return Json(!l, JsonRequestBehavior.AllowGet);

            //            return Json(!dataManager.IsPhoneExists(e_mail, Код), JsonRequestBehavior.AllowGet);
        }

 


        [Authorize(Users = "Admin")]
        public ActionResult NotesListAdmin()
        {
            return View("_PartialNotesIndex", dataManager.GetNotes(-13));
        }


        public ActionResult NotesListIndex()
        {
            return PartialView("_PartialNotesIndex", dataManager.GetNotes());
        }


        public ActionResult NotesList(int? id)
        {
            return PartialView("_PartialNotesList", dataManager.GetNotesFromIdPeople(id));
        }

Views/Shared/_Layout.cshtml
@using CuatroCaminosMvcApplication
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="robots" content="NOINDEX, NOFOLLOW" />

    <title>@ViewBag.Title</title>

    <link href="@Url.Content("~/Content/boilerplate.css")" rel="stylesheet" type="text/css" />
@*    <link href="@Url.Content("~/Content/vadim.css")" rel="stylesheet" type="text/css" />*@
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-1.8.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.9.0.min.js")" type="text/javascript"></script>


    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
 


@*    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script> 
*@

</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>"Клуб Танцев"</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Новости", "Index", "Home")</li>
                    <li>@Html.ActionLink("Оплата", "Index", "Payment")</li>
                    <li>@Html.ActionLink("Мероприятия", "Index", "Activity")</li>
                    <li>@Html.ActionLink("Списки людей", "Index", "People")</li>

@if (HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора)
{
        <li>@Html.ActionLink("Визиты", "Index", "Visits")</li>
        <li>@Html.ActionLink("Касса", "Index", "Cash")</li>    
        <li>@Html.ActionLink("Админ", "Index", "Admin")</li>
    
}
                    <li>@Html.ActionLink("Помощь", "Help", "Home")</li> 

                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

Views/Shared/_LayoutExtended.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
	@*<meta name="copyright" content="© 2011" />
	<meta name="Robots" content="all" />
	<meta name="document-state" content="dynamic" />
	<meta name="revisit" content="7 days" />
	<meta name="revisit-after" content="7 days" />
	<meta http-equiv="Pragma" content="no-cache" />
	<meta name="viewport" content="width=device-width" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta name="description" content="описание сайта" />
	<meta name="keywords" content="ключевые слова сайта" />
	<link rel="Shortcut Icon" href="@Url.Content("~/favicon.ico")" />*@
	<link href="@Url.Content("/Content/Site.css")" rel="stylesheet" type="text/css" />
	@*<link href="@Url.Content("/Content/themes/jquery-ui-1.8.21.custom.css")" rel="stylesheet" type="text/css" />*@
	@RenderSection("header", false)
</head>
<body>
	<div class="page">
		<header>
			<div id="title">
				<h1>Заголовок</h1>
			</div>
			<div id="logindisplay">
			@Html.Partial("_LogOnPartial")
		</div>
			<nav>
				<ul id="menu">
					<li>@Html.ActionLink("Главная", "index", "home")</li>
					<li>@Html.ActionLink("О проекте", "about", "home")</li>
				</ul>
			</nav>
		</header>
		<div id="main">
			@RenderBody()
		</div>
		<footer>все права защищены @( DateTime.Now.Year.ToString())	© компания<br/>
			программирование <a href="#">название компания</a></footer>
	</div>
	@Content.Scripts("jquery-1.7.2.min.js", Url)
	@Content.Scripts("jquery.unobtrusive-ajax.min.js", Url)
	@Content.Scripts("modernizr-2.5.3.js", Url)
	@*@Content.Scripts("jquery-ui-1.8.21.custom.min.js", Url)*@
	@RenderSection("scripts", false)
	@Html.WriteScriptBlocks()
</body>
</html>

Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Добро пожаловать, <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Выход", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Вход", "LogOn", "Account") ]
}

Views/Shared/_PartialPeopleColor.cshtml
<br/>
<hr/>

   <i> Цветовая расшифровка:</i>

<ul>
    <li style="color: #6600FF">мужчина</li>
    <li style="color: red">нет номера телефона</li>
    <li style="background-color: whitesmoke">выбыл из школы</li>

</ul>