Controllers/ExportController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Web.Mvc;
using CuatroCaminosMvcApplication.Models;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using iTextSharp.text.rtf.headerfooter;
using iTextSharp.text.xml;
using Color = iTextSharp.text.Color;
using Font = iTextSharp.text.Font;


namespace CuatroCaminosMvcApplication.Controllers
{
    [Authorize]
    public class ExportController : Controller
    {
        private static String fontsDirName = (AppDomain.CurrentDomain.BaseDirectory + "fonts");
        private static BaseFont baseFont = BaseFont.CreateFont(fontsDirName + "\\arial.ttf", BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);

        iTextSharp.text.Font fontLarge = new iTextSharp.text.Font(baseFont, 16, iTextSharp.text.Font.BOLD);
        iTextSharp.text.Font font = new iTextSharp.text.Font(baseFont, iTextSharp.text.Font.DEFAULTSIZE, iTextSharp.text.Font.NORMAL);
        iTextSharp.text.Font fontSmail = new iTextSharp.text.Font(baseFont, 11, iTextSharp.text.Font.NORMAL, Color.BLACK);
        iTextSharp.text.Font fontSmailer = new iTextSharp.text.Font(baseFont, 9, iTextSharp.text.Font.NORMAL, Color.BLACK);


 //       iTextSharp.text.Font font, fontSmail, fontLarge, fontSmailer;
 //       private PdfContentByte pdfContent;
 //       private PdfTemplate pageNumberTemplate;
 //       private DateTime printTime;
        private PdfPCell cell;


        PdfPTable table = new PdfPTable(14);

        Document document = new Document(iTextSharp.text.PageSize.A4.Rotate(), 5, 5, 5, 5);
        MemoryStream memoryStream = new MemoryStream();


        DataManager dataManager = new DataManager();


        public FileResult Index(int gruppa)
        {

//            gruppa = Request.QueryString["Group"]}

//            int gruppa = collection["gruppa"] != null ? Convert.ToInt32(collection["gruppa"]) : 0;

            ICollection<List_IdAndName> listIdAndNames = dataManager.GetExportСписокОплаты(gruppa);




            

            PdfWriter pdfWriter =  PdfWriter.GetInstance(document, memoryStream);
            PdfContentByte pdfContentByte = new PdfContentByte(pdfWriter);

//            PdfTextArray pdfTextArray = new PdfTextArray(String.Format("                 Список оплаты Клуба Танцев \"Cuatro Caminos\".       группа: {0}", dataManager.GetNameGroupFromId(gruppa)));

            pdfWriter.CloseStream = false;

            var welcomeParagraph = new Paragraph(String.Format("     Список оплаты Клуба Танцев \"Cuatro Caminos\".          {0}             месяц: _____________ {1}", dataManager.GetNameGroupFromId(gruppa), DateTime.Now.Year), fontLarge);

            HeaderFooter headerFooter = new HeaderFooter(
                    new Phrase("Всего: " + listIdAndNames.Count + " человек                                                  " + "описание группы: " + dataManager.GetDescGroupFromId(gruppa) + "                                                                   " + DateTime.Now.ToString("dd-MM-yyyy HH:mm") + "                ", fontSmailer), true);

            headerFooter.Border = iTextSharp.text.Rectangle.NO_BORDER;
            headerFooter.Alignment = 2;
            headerFooter.Top = 0;
            headerFooter.Bottom = 0;


            document.Footer = headerFooter;
            headerFooter.Top = 0;
            headerFooter.Bottom = 0;
//            headerFooter.Before = welcomeParagraph;   


            document.Open();


            document.AddTitle("Список оплаты Клуба Танцев \"Cuatro Caminos\"");
            document.AddAuthor("Вадим");
            
            document.Add(welcomeParagraph);


//            HeaderFooter headerFooter= new HeaderFooter();


//            table = new PdfPTable(14);

            table.TotalWidth = 830f;
            //fix the absolute width of the table
            table.LockedWidth = true;

            //relative col widths in proportions - 1/3 and 2/3
            float[] widths = new float[] { 3f, 1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f };
            table.SetWidths(widths);
            table.HorizontalAlignment = 0;
            //leave a gap before and after the table
            table.SpacingBefore = 20f;
            table.SpacingAfter = 30f;


            int ii = 1;


//            PdfPCell cell_fio;

           

            foreach (var item in listIdAndNames)
            {


                if (ii == 1 || ii == 21 || ii == 42)
                {
                    ShapkaTable();
                }


                cell = new PdfPCell(new Phrase(String.Format(" {1}", ii, item.Names), fontSmail));

                cell.PaddingBottom = 6f;
                cell.PaddingTop = 6f;


                table.AddCell(cell);

                for (int i = 0; i < 13; i++)
                {
                 table.AddCell("");   
                }

                ii++;
            }

            if (listIdAndNames.Count<21)
            {
                for (int i = 0; i < 41 - listIdAndNames.Count; i++)
                {
                    cell = new PdfPCell(new Phrase(""));

                    cell.PaddingBottom = 19f;

                    table.AddCell(cell);

                    for (int a = 0; a < 13; a++)
                    {
                        table.AddCell("");
                    }

                }
                
            }

                FooterTable();
            

            document.Add(table);

            document.Close();

            byte[] bytes = new byte[memoryStream.Position];
            memoryStream.Position = 0;
            memoryStream.Read(bytes, 0, bytes.Length);


            return File(bytes, "application/pdf", "PhoneEport_.pdf");
        }

        private PdfPTable ShapkaTable()
        {


            cell = new PdfPCell(new Phrase("ФИО", fontLarge));
            //            cell.BackgroundColor = new Color(0, 150, 0);
            //            cell.BorderColor = new Color(255, 242, 0);
            //            cell.Border = iTextSharp.text.Rectangle.BOTTOM_BORDER | iTextSharp.text.Rectangle.TOP_BORDER;
            //            cell.BorderWidthBottom = 3f;
            //            cell.BorderWidthTop = 3f;
            cell.PaddingBottom = 10f;
            //            cell.PaddingLeft = 15f;
            cell.PaddingTop = 10f;


            cell.VerticalAlignment = 1;
            cell.HorizontalAlignment = 1;

//            PdfPTable table = new PdfPTable(14);

            table.AddCell(cell);

            table.AddCell(new Phrase(new Chunk("Перенос с прошлого месяца", fontSmailer)));

            for (int i = 1; i < 13; i++)
            {
                table.AddCell(new Phrase(new Chunk(String.Format("{0} занятие", i), fontSmailer)));
            }

//            headerFooter = new  RtfHeaderFooter(table);

            return table;
        }

        private PdfPTable FooterTable()
        {


            cell = new PdfPCell(new Phrase(new Chunk("Сумма за день", font)));
            cell.VerticalAlignment = 2;
            cell.HorizontalAlignment = 1;
            cell.Colspan = 2;
            cell.PaddingBottom = 15f;
            cell.PaddingTop = 15f;



            table.AddCell(cell);

            for (int i = 1; i < 13; i++)
            {

                table.AddCell(new Phrase(new Chunk(String.Format("{0} занятие", i), fontSmailer)));
            }




            cell = new PdfPCell(new Phrase(new Chunk("Количество людей", font)));
            cell.Colspan = 2;
            cell.PaddingBottom = 7f;
            cell.PaddingTop = 7f;
            cell.VerticalAlignment = 1;
            cell.HorizontalAlignment = 1;

            table.AddCell(cell);


            for (int i = 1; i < 13; i++)
            {
                table.AddCell("");
            }




            
            cell = new PdfPCell(new Phrase(new Chunk("Тренер", font)));
            cell.Colspan = 2;
            cell.PaddingBottom = 7f;
            cell.PaddingTop = 7f;
            cell.VerticalAlignment = 1;
            cell.HorizontalAlignment = 1;

            table.AddCell(cell);


            for (int i = 1; i < 13; i++)
            {
                table.AddCell("");
            }

            return table;
        }



    }
}

Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuatroCaminosMvcApplication.Models;
using System.Data.Entity;

namespace CuatroCaminosMvcApplication.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        //
        // GET: /payment/

        private Cuatro_Caminos_BDEntities db = new Cuatro_Caminos_BDEntities();


        DataManager dataManager = new DataManager();


        public ActionResult PartialОплата(int id)
        {

            return PartialView("_PartialОплата", dataManager.GetОплатаFromФИО(id));
        }

        public ActionResult Group()
        {
            return View(dataManager.GetPayGroup());
        }


        [CookieFilter]
        public ActionResult List()
        {
            SetViewBag();
            return View(dataManager.GetОплатаData());
        }




        [CookieFilter(Order = 1)]
        [RoleFilter(Order = 10)]
        public ActionResult Index()
        {
            SetViewBag();
            return View(dataManager.GetОплата());
        }


        
        [HttpPost]
        [CookieFilter(Order = 1)]
        [RoleFilter(Order = 10)]
        public ActionResult Index(FormCollection collection)
        {


            SetViewBag();
            return View(dataManager.GetОплата());
        }


        //
        // GET: /payment/Details/5

        public ActionResult GroupSummary(int? month)
        {

            if (month == 13)
            {
                month = DateTime.Now.AddMonths(-1).Month;
            }

            GroupSummaryViewModel groupSummaryViewModel = new GroupSummaryViewModel(dataManager.GetОплата(month));

            return View(groupSummaryViewModel.Get());
        }

        public ActionResult Details(int id)
        {


//            int loginRecId = dataManager.GetIdFromОплатаLoginRecId(id);
            Списки_людей спискиЛюдей = dataManager.GetPeapleFioFromId(dataManager.GetIdFromОплатаLoginRecId(id));

            ViewBag.LoginRecFio = спискиЛюдей.ФИО;

            return View(dataManager.GetОплата(id));

        
        }

        //
        // GET: /payment/Create

//        [CookieFilter]
        public ActionResult Create()
        {


//            ViewBag._Преподаватель = dataManager.SelectListИменаПреподавателей(FromFormData.Преподаватель);
//            ViewBag.ФИО = dataManager.ListСписокВсехФио();
            ViewBag._Код_Ученика = dataManager.SelectListСписокФио(FromFormData.Код_Ученика); 
            ViewBag._Название_танца = dataManager.SelectListСписокНаправленийТанцев(FromFormData.Название_танца);
            ViewBag._Преподаватель = dataManager.SelectListИменаПреподавателей(FromFormData.Преподаватель);


            ViewBag.Дата = FromFormData.Дата_оплаты;

            return View();
        } 

        //
        // POST: /payment/Create

//        [CookieFilter]
        [HttpPost]
        public ActionResult Create(Оплата оплата, FormCollection collection)
        {

            dataManager.CreateОплата(оплата);
            
            // TODO: Add insert logic here


            try
            {
               
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /payment/Edit/5


//        [Authorize(Users = "admin")]
        public ActionResult Edit(int id)
        {

            Оплата оплата = dataManager.GetОплата(id);
            ViewBag._Преподаватель = dataManager.SelectListИменаПреподавателей(оплата.Преподаватель);
            ViewBag.ФИО = dataManager.ListСписокВсехФио();
//            ViewBag._Код_Ученика = dataManager.SelectListСписокФио(оплата.Код_Ученика);
//            ViewBag.Fio = dataManager.GetСписокФиоFromGroup() оплата.Код_Ученика;
            ViewBag._Название_танца = dataManager.SelectListВсехСписокНаправленийТанцев(оплата.Названия_танцев.Код);

            ViewBag.Дата = оплата.Дата_оплаты.Date;

            Списки_людей спискиЛюдей = dataManager.GetPeapleFioFromId(dataManager.GetIdFromОплатаLoginRecId(id));
            ViewBag.LoginRecFio = спискиЛюдей.ФИО;





            return View(dataManager.GetОплата(id));
        }

        //
        // POST: /payment/Edit/5

        [HttpPost]
        [CookieFilter]
        public ActionResult Edit(int id, FormCollection collection)
        {


            Оплата оплата = dataManager.GetОплата(id);

            оплата.Месяц = Convert.ToDateTime(collection["Дата_оплаты"]).Month;
            оплата.DateTimeRec = DateTime.Now;
            оплата.LoginRecId = dataManager.GetFromLoginToId(HttpContext.User.Identity.Name); 

            UpdateModel(оплата);
            
            dataManager.SaveChanges();


            try
            {
                // TODO: Add update logic here


                return Redirect("/payment/details/"+id);
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /payment/Delete/5
 
        public ActionResult Delete(int id)
        {


            return View(dataManager.GetОплата(id));
        }

        //
        // POST: /payment/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {

            dataManager.DeleteОплата(id);
 

            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Month(int? id, int? month, int? gruppa, FormCollection collection)
        {

            VisitsDataManager visitsDataManager = new VisitsDataManager();
            MyEntityViewModel viewModel = new MyEntityViewModel(dataManager.GetMonthОплата(month, gruppa), visitsDataManager.GetSumm());
            ViewBag.NameGroup = dataManager.GetNameGroupFromIdAndDescriptoin(gruppa);

//            ViewBag.Оплата = dataManager.GetMonthОплата(DateTime.Now.Month);
            return View(viewModel);
        }

        
        
        [CookieFilter]
        public PartialViewResult ListPayPartial()
        {

            ICollection<Оплата> оплата = dataManager.GetОплатаListPartial(DateTime.Now);
            return PartialView("_PartialОплата", оплата);
        }



        [HttpPost]
//        [CookieFilter]
        public PartialViewResult CreateAjax(Оплата оплата, FormCollection collection)
        {

            dataManager.CreateОплата(оплата);

            // TODO: Add insert logic here


            try
            {
                ICollection<Оплата> оплата1 = dataManager.GetОплатаListPartial(оплата.Дата_оплаты, оплата.Названия_танцев.Код);
                return PartialView("_PartialОплата", оплата1);
            }
            catch
            {
                return PartialView();
            }
        }





        private void SetViewBag()
        {
            ViewBag.month = dataManager.SelectListСписокМесяцев(FromFormData.month);
            ViewBag.Название_танца = dataManager.SelectListСписокНаправленийТанцев(FromFormData.Название_танца);
            ViewBag.Код_Ученика = dataManager.SelectListСписокФиоОтОплаты(FromFormData.Код_Ученика, null);
            ViewBag.Преподаватель = dataManager.SelectListИменаПреподавателей(FromFormData.Преподаватель);
        }




    }
}

Views/Payment/Delete.cshtml
@using CuatroCaminosMvcApplication
@model CuatroCaminosMvcApplication.Models.Оплата

@{
    ViewBag.Title = "Удаление оплаты";
    DateTime dateTime = DateTime.Now;

}

<h2>Удаление оплаты</h2>

<h3>Вы уверены, что хотите безвовратно удалить эту запись?</h3>
<fieldset>
    <legend>Оплата</legend>

    <div class="display-label">Дата оплаты</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Дата_оплаты)
    </div>

    <div class="display-label">ФИО</div>
    <div class="display-field">
       @Html.DisplayFor(modelItem => Model.Списки_людей.Фамилия) 
       @Html.DisplayFor(modelItem => Model.Списки_людей.Имя) 
       @Html.DisplayFor(modelItem => Model.Списки_людей.Отчество)
    </div>


    <div class="display-label">Сумма, руб.</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Сумма)
    </div>

    <div class="display-label">Примечание</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Примечание)
    </div>

    <div class="display-label">Преподаватель</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Имена_преподавателей.ФИО)
    </div>

    <div class="display-label">Название группы</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Названия_танцев.Название_танца)
    </div>
</fieldset>

@{
    dateTime = Model.DateTimeRec?? DateTime.Now.AddDays(111);
}


@using (Html.BeginForm()) {
    <p>
        @if (dateTime.Date == DateTime.Now.Date || HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора)
        {
            @:<input type="submit" value="Удалить" /> |
        }else
        {
            <ul>
                <h5>Вы не можете удалять оплату "задним числом"</h5>
            </ul>
        } 

        @Html.ActionLink("Вернуться в список", "Index")
    </p>
}

Views/Payment/Details.cshtml
@using CuatroCaminosMvcApplication.Models
@model CuatroCaminosMvcApplication.Models.Оплата
           

@{
    ViewBag.Title = "Детали оплаты";
}

<h2>Детали оплаты</h2>

<fieldset>
    <legend>Оплата</legend>

    <div class="display-label">Дата оплаты</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Дата_оплаты)
    </div>

    <div class="display-label">ФИО</div>
    <div class="display-field">
       @Html.DisplayFor(modelItem => Model.Списки_людей.Фамилия) 
       @Html.DisplayFor(modelItem => Model.Списки_людей.Имя) 
       @Html.DisplayFor(modelItem => Model.Списки_людей.Отчество)
    </div>

@*    <div class="display-label">Месяц</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Месяц)
    </div>
*@
    <div class="display-label">Сумма, руб.</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Сумма)
    </div>

    <div class="display-label">Примечание</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Примечание)
    </div>

    <div class="display-label">Преподаватель</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Имена_преподавателей.ФИО)
    </div>

    <div class="display-label">Название группы</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Названия_танцев.Название_танца) 
     =   
        @Html.DisplayFor(model => model.Названия_танцев.Description) 
     =
    </div>

<br/>
<hr/>

    <div class="display-label">Время внесения записи</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateTimeRec)
    </div>

    <div class="display-label">Кто записал оплату</div>
    <div class="display-field">
        @ViewBag.LoginRecFio
    </div>


</fieldset>

<p>

    @Html.ActionLink("Назад к списку оплаты", "Index") | 


        @if (Model.Списки_людей.Код != 151)
        {
           @Html.ActionLink("Карточка клиента", "Details", "People", new {id = Model.Код_Ученика}, null) @:|
        }
        
    @Html.ActionLink("Редактировать оплату", "Edit", new { id = Model.Код }) |
    @Html.ActionLink("Удалить оплату", "Delete", new { id = Model.Код}) |


</p>

Views/Payment/GroupSummary.cshtml
@model IEnumerable<CuatroCaminosMvcApplication.Models.PayGroup>

@{
    ViewBag.Title = "Общие суммы по группам";
}

<h2>Общие суммы по группам</h2>

<p>
    @Html.ActionLink("Вернуться в оплату", "Index", "Payment") |

</p>

<table>
    <tr>
        <th>
            Месяц
        </th>
        <th>
            Год
        </th>
        <th>
            Сумма
        </th>
        <th>
            Кол-во <br/> людей
        </th>

        <th>
            Группа
        </th>
        <th>
            
        </th>
        <th>
           Создана 
        </th>

@*        <th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date.Month)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date.Year)
        </td>
        <td class="many"> 
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PeopleCount)
           

        </td>

        <td>
            @Html.ActionLink(item.Group, "Month", "Payment", new { month = item.Date.Month, gruppa = item.GroupId}, null) 
            @*            @Html.DisplayFor(modelItem => item.Group)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GroupDescr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GroupDateTimeRec)
        </td>

@*        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>

<hr/>

<strong>
    Всего @Html.Label(Model.Count().ToString()) записей, на сумму: @Model.Select(item => item.Amount).Sum() руб.
</strong>
<br/>

Views/Payment/Index.cshtml
@using CuatroCaminosMvcApplication
@using CuatroCaminosMvcApplication.Models


           
@{

    ViewBag.Title = "Отчет по оплате";
}
<h2>Отчет по оплате</h2>
<p>
    


    @using(@Html.BeginForm()){
    
        @Html.DropDownList("month", "Все месяца");
        @: | 
        @Html.DropDownList("Название_танца", "Все группы");
@*
        @: | 

        @Html.DropDownList("Код_Ученика", "Все ученики");
*@
        if (HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора)
        {
      
            @: | 

            @Html.DropDownList("Преподаватель", "Все преподаватели");
        }

        <input type="submit" value="Фильтр"/>


    }
    <br/>
    @Html.ActionLink("Внести новую оплату", "Create") | 
    @Html.ActionLink("Развернутый отчет", "Month", new { month = FromFormData.month, gruppa = FromFormData.Название_танца }, null) |
    @Html.ActionLink("Список оплаты", "Index", "Export", new { month = FromFormData.month, gruppa = FromFormData.Название_танца }, null) |
    @Html.ActionLink("Суммы по группам", "GroupSummary", new { month = FromFormData.month },  new { style = "color: red" })



</p>

@Html.Partial("_PartialОплата")
@Html.Partial("_PartialPeopleColor")

Views/Payment/Month.cshtml
@using System.Globalization
@using System.Threading
@using CuatroCaminosMvcApplication.Models
@using CuatroCaminosMvcApplication.MyHtmlHelpers;
@model MyEntityViewModel

<h2>Отчет по оплате: @ViewBag.NameGroup</h2>



@{
    int item = 0;
    var _valuex=0;
    int[] _valuey = new int[1000];

    int many=0;

    string fio;
    
    System.Globalization.CultureInfo ci = new System.Globalization.CultureInfo("ru-RU");

    
    CultureInfo cultureInfo = new CultureInfo("ru-RU");
//    cultureInfo.DateTimeFormat.FirstDayOfWeek = DayOfWeek.Monday;
//    Thread.CurrentThread.CurrentCulture = cultureInfo; 


}
<p>
    @Html.ActionLink("Назад", "Index") | 
    @Html.ActionLink("Внести новую оплату", "Create") |
    @Html.ActionLink("Список оплаты", "Index", "Export", new {gruppa = Request.QueryString["gruppa"]}, null) 
</p>

@*<p>
    @Html.ActionLink("Месяц назад", "Month", ) | 

</p>
*@

@if (Model.Names.Count >0){

<table>
<tr>
    <th class="date">
        Имя
    </th>
    @foreach (var date in Model.Dates)
    {
         <th class="date">
             @Html.Encode(date.ToString("d")) 
                 <br />
             @Html.Encode(ci.DateTimeFormat.GetDayName((DayOfWeek)date.DayOfWeek))

             
@*
           @{
                     ci.DateTimeFormat.GetDayName((DayOfWeek)date.DayOfWeek);
                     int delta = date.DayOfWeek - Thread.CurrentThread.CurrentCulture.DateTimeFormat.FirstDayOfWeek + 1;
                 
                 @delta
             }
*@         

     </th>
    }
@*    <th>Остаток</th>*@
    <th>ИТОГО</th>
</tr>

@foreach (List_IdAndName name in Model.Names)
{
     <tr>
        <td class="fio">
            
    @{fio = name.Names;}                

            @if (Model[name.Names] == 151)
            {
            
                @Html.Encode(fio)   
            }
            else
            {
                @Html.ActionLink(fio, "Details", "People", new { id = name.Id }, null)
            }


        </td>
        
        @foreach (var date in Model.Dates)
        {
            <td  class="many">


                @{
                    //                  @Html.Encode(Model[name, date] != 0 ? Model[name, date] : null)

                    many = Model[name.Names, date] ?? 0;


                    if (Model.GetIdPayCount(fio, date) != 1)
                    {
                        @Html.Encode(Model[fio, date] != 0 ? Model[name.Names, date] : null)
                    }
                    else
                    {
                        @Html.ActionLink((many != 0 ? many.ToString() : " "), "Edit", "Payment", new { id = @Model.GetIdPay(fio, date)  }, null)

                    }



                    if (Model[fio, date] != null)
                    {

                    
                        _valuex += Convert.ToInt32(Model[fio, date]);
                        _valuey[item] += Convert.ToInt32(Model[fio, date]);

@*                       @Html.GetVisit(fio, date)
                       
                    @Model.PaySumm(fio)
                    @: ,
                    @Model.Visit(fio)
                    @: ,
                    @Model.Freezing(fio)
                    @: ,
                    @Model.hghg(fio)

                    @: ,
                    @Model.LastPrice8()

                    
                    @: , --
//                    @Model .GetLastPrice11(1)
*@
                        

                       
                        
                    
                    
                    }
                  

                    item++;

                }
            </td>
        }
        
        


        <th class="many">
        
        @_valuex  
        
        @{
        _valuex = 0;
        item = 0;
         }
        </th>
     </tr>
}


    <tr>
                <th> </th>



        @foreach (var date in Model.Dates)
        {
         <th class="date">
             @Html.Encode(date.ToString("d"))
         </th>
        }
    </tr>


    <tr>
                <th>Сумма</th>

        @foreach (var date in Model.Dates)
        {
             <th class="many">

                  @Html.Encode(_valuey[item])
                  @{item++;}
             </th>
        }



    </tr>



</table>
    <br/><br/>
    <text>    
                Всего: @Model.Names.Count записей.
    </text>
}

<br/><br/>
    @Html.ActionLink("Назад", "Index") | 
    @Html.ActionLink("Внести новую оплату", "Create") 