Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuatroCaminosMvcApplication.Models;
using System.Data.Entity;

namespace CuatroCaminosMvcApplication.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        //
        // GET: /payment/

        private Cuatro_Caminos_BDEntities db = new Cuatro_Caminos_BDEntities();


        DataManager dataManager = new DataManager();


        public ActionResult PartialОплата(int id)
        {

            return PartialView("_PartialОплата", dataManager.GetОплатаFromФИО(id));
        }

        public ActionResult Group()
        {
            return View(dataManager.GetPayGroup());
        }


        [CookieFilter]
        public ActionResult List()
        {
            SetViewBag();
            return View(dataManager.GetОплатаData());
        }




        [CookieFilter(Order = 1)]
        [RoleFilter(Order = 10)]
        public ActionResult Index()
        {
            SetViewBag();
            return View(dataManager.GetОплата());
        }


        
        [HttpPost]
        [CookieFilter(Order = 1)]
        [RoleFilter(Order = 10)]
        public ActionResult Index(FormCollection collection)
        {


            SetViewBag();
            return View(dataManager.GetОплата());
        }


        //
        // GET: /payment/Details/5

        public ActionResult GroupSummary(int? month)
        {

            if (month == 13)
            {
                month = DateTime.Now.AddMonths(-1).Month;
            }

            GroupSummaryViewModel groupSummaryViewModel = new GroupSummaryViewModel(dataManager.GetОплата(month));

            return View(groupSummaryViewModel.Get());
        }

        public ActionResult Details(int id)
        {


//            int loginRecId = dataManager.GetIdFromОплатаLoginRecId(id);
            Списки_людей спискиЛюдей = dataManager.GetPeapleFioFromId(dataManager.GetIdFromОплатаLoginRecId(id));

            ViewBag.LoginRecFio = спискиЛюдей.ФИО;

            return View(dataManager.GetОплата(id));

        
        }

        //
        // GET: /payment/Create

//        [CookieFilter]
        public ActionResult Create()
        {


//            ViewBag._Преподаватель = dataManager.SelectListИменаПреподавателей(FromFormData.Преподаватель);
//            ViewBag.ФИО = dataManager.ListСписокВсехФио();
            ViewBag._Код_Ученика = dataManager.SelectListСписокФио(FromFormData.Код_Ученика); 
            ViewBag._Название_танца = dataManager.SelectListСписокНаправленийТанцев(FromFormData.Название_танца);
            ViewBag._Преподаватель = dataManager.SelectListИменаПреподавателей(FromFormData.Преподаватель);


            ViewBag.Дата = FromFormData.Дата_оплаты;

            return View();
        } 

        //
        // POST: /payment/Create

//        [CookieFilter]
        [HttpPost]
        public ActionResult Create(Оплата оплата, FormCollection collection)
        {

            dataManager.CreateОплата(оплата);
            
            // TODO: Add insert logic here


            try
            {
               
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /payment/Edit/5


//        [Authorize(Users = "admin")]
        public ActionResult Edit(int id)
        {

            Оплата оплата = dataManager.GetОплата(id);
            ViewBag._Преподаватель = dataManager.SelectListИменаПреподавателей(оплата.Преподаватель);
            ViewBag.ФИО = dataManager.ListСписокВсехФио();
//            ViewBag._Код_Ученика = dataManager.SelectListСписокФио(оплата.Код_Ученика);
//            ViewBag.Fio = dataManager.GetСписокФиоFromGroup() оплата.Код_Ученика;
            ViewBag._Название_танца = dataManager.SelectListВсехСписокНаправленийТанцев(оплата.Названия_танцев.Код);

            ViewBag.Дата = оплата.Дата_оплаты.Date;

            Списки_людей спискиЛюдей = dataManager.GetPeapleFioFromId(dataManager.GetIdFromОплатаLoginRecId(id));
            ViewBag.LoginRecFio = спискиЛюдей.ФИО;





            return View(dataManager.GetОплата(id));
        }

        //
        // POST: /payment/Edit/5

        [HttpPost]
        [CookieFilter]
        public ActionResult Edit(int id, FormCollection collection)
        {


            Оплата оплата = dataManager.GetОплата(id);

            оплата.Месяц = Convert.ToDateTime(collection["Дата_оплаты"]).Month;
            оплата.DateTimeRec = DateTime.Now;
            оплата.LoginRecId = dataManager.GetFromLoginToId(HttpContext.User.Identity.Name); 

            UpdateModel(оплата);
            
            dataManager.SaveChanges();


            try
            {
                // TODO: Add update logic here


                return Redirect("/payment/details/"+id);
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /payment/Delete/5
 
        public ActionResult Delete(int id)
        {


            return View(dataManager.GetОплата(id));
        }

        //
        // POST: /payment/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {

            dataManager.DeleteОплата(id);
 

            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Month(int? id, int? month, int? gruppa, FormCollection collection)
        {

            VisitsDataManager visitsDataManager = new VisitsDataManager();
            MyEntityViewModel viewModel = new MyEntityViewModel(dataManager.GetMonthОплата(month, gruppa), visitsDataManager.GetSumm());
            ViewBag.NameGroup = dataManager.GetNameGroupFromIdAndDescriptoin(gruppa);

//            ViewBag.Оплата = dataManager.GetMonthОплата(DateTime.Now.Month);
            return View(viewModel);
        }

        
        
        [CookieFilter]
        public PartialViewResult ListPayPartial()
        {

            ICollection<Оплата> оплата = dataManager.GetОплатаListPartial(DateTime.Now);
            return PartialView("_PartialОплата", оплата);
        }



        [HttpPost]
//        [CookieFilter]
        public PartialViewResult CreateAjax(Оплата оплата, FormCollection collection)
        {

            dataManager.CreateОплата(оплата);

            // TODO: Add insert logic here


            try
            {
                ICollection<Оплата> оплата1 = dataManager.GetОплатаListPartial(оплата.Дата_оплаты, оплата.Названия_танцев.Код);
                return PartialView("_PartialОплата", оплата1);
            }
            catch
            {
                return PartialView();
            }
        }





        private void SetViewBag()
        {
            ViewBag.month = dataManager.SelectListСписокМесяцев(FromFormData.month);
            ViewBag.Название_танца = dataManager.SelectListСписокНаправленийТанцев(FromFormData.Название_танца);
            ViewBag.Код_Ученика = dataManager.SelectListСписокФиоОтОплаты(FromFormData.Код_Ученика, null);
            ViewBag.Преподаватель = dataManager.SelectListИменаПреподавателей(FromFormData.Преподаватель);
        }




    }
}

Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI;
using CuatroCaminosMvcApplication.Models;


namespace CuatroCaminosMvcApplication.Controllers
{

    [Authorize]
    //    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class PeopleController : Controller
    {
        //
        // GET: /СпискиЛюдей/

        private Cuatro_Caminos_BDEntities db = new Cuatro_Caminos_BDEntities();

        //        private string[] alfavit = new string[] { "А", "Б", "В", "Г", "Д", "Е", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" };

        DataManager dataManager = new DataManager();

        public ActionResult Index(FormCollection collection, int? page, char? alfavit)
        {

            //            dataManager.GetPeaple();
            //int pageSize = 3;
            //int pageIndex = (page ?? 1) - 1; 

            ViewBag.Alfavit = dataManager.GetAlfavitFromФИО();


            return View(dataManager.GetPeaple(alfavit));
        }


        public ActionResult Group(int? group)
        {

            ViewBag.Название_танцев = dataManager.GetНазваниеТанцев();
            ViewBag.Имя_группы = dataManager.GetNameGroupFromId(group);
            Названия_танцев singleOrDefault = dataManager.GetНазваниеТанцев().SingleOrDefault(i => i.Код == @group);
            if (singleOrDefault != null)
                ViewBag.Description = singleOrDefault.Description;


            return View(dataManager.GetСписокФиоFromGroup(group));
        }


        public ActionResult Schools(int schools)
        {

            ICollection<Списки_людей> спискиЛюдей = dataManager.GetPeapleSchools(schools);
            Название_школ названиеШколы = dataManager.GetНазваниеШкол(schools);

            string названиеШкол = null;

            if (названиеШколы != null)
            {
                названиеШкол = названиеШколы.Школы;
            }

            ViewBag.School = String.Format(" '{0}' ", названиеШкол);

            ViewBag.Schools = dataManager.GetНазваниеШкол();


            return View(спискиЛюдей);
        }


        public ActionResult DoNotGo(int? group, int? day)
        {

            IDictionary<int, string> days = new Dictionary<int, string>();
            //            days.Add(-7, "1 неделю");
            //            days.Add(-14, "2 недели");
            //            days.Add(-21, "3 недели");
            days.Add(-30, "1 месяц");
            //            days.Add(-45, "1,5 месяца");
            days.Add(-60, "2 месяца");
            days.Add(-90, "3 месяца");

            ViewBag.Название_танцев = dataManager.GetНазваниеТанцев();
            ViewBag.Имя_группы = dataManager.GetNameGroupFromId(group);
            ViewBag.Days = days;

            return View(dataManager.GetPeapleDoNotGo(group, day));
        }




        //
        // GET: /СпискиЛюдей/Details/5

        public ActionResult Details(int id)
        {

            //            ViewData["Оплата"] = dataManager.GetОплатаFromФИО(id);
            int LoginRecId = dataManager.ListСписокВсехФио().Where(e => e.Код==id).Select(e=>e.LoginRecId).SingleOrDefault();
            Списки_людей спискиЛюдей = dataManager.GetPeapleFioFromId(LoginRecId);
            ViewBag.LoginRecFio = спискиЛюдей.ФИО;



            return View(dataManager.GetPeaple(id));
        }



        //
        // GET: /СпискиЛюдей/Create

        public ActionResult Create()
        {
            SetViewBag();
            ViewBag._Школы = dataManager.SelectListСписокВсехШкол(7);
            ViewBag._Название_SMS = dataManager.SelectListSms(1);

            return View();
        }

        //
        // POST: /СпискиЛюдей/Create

        [HttpPost]
        public ActionResult Create(Списки_людей спискиЛюдей, FormCollection collection)
        {

            //               ViewBag._Message = String.Format("Записись сохранена");

            // TODO: Add insert logic here


            dataManager.CreateНовыйКлиент(спискиЛюдей);
            return RedirectToAction("Index");


            //if (ModelState.IsValid)
            //{
            //    dataManager.CreateНовыйКлиент(спискиЛюдей);
            //    return RedirectToAction("Index");
            //}
            //else
            //{
            //    SetViewBag();
            //    return View();
            //}


        }

        //
        // GET: /СпискиЛюдей/Edit/5

        public ActionResult Edit(int id)
        {
            Списки_людей спискиЛюдей = dataManager.GetPeaple(id);


            SetViewBag(спискиЛюдей);

            return View(спискиЛюдей);
        }

        //
        // POST: /СпискиЛюдей/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {



            try
            {
                // TODO: Add update logic here

                if (ModelState.IsValid)
                {
                    Списки_людей спискиЛюдей = dataManager.GetPeaple(id);

                    спискиЛюдей.DateTimeRec = DateTime.Now;
                    спискиЛюдей.LoginRecId = dataManager.GetFromLoginToId(HttpContext.User.Identity.Name);

                    //if (collection["Выбыл_из_школы"] != "false")
                    //{
                    //    if (спискиЛюдей.Дата_выбытия == null)
                    //    {
                    //        спискиЛюдей.Дата_выбытия = DateTime.Now;
                    //    }

                    //}
                    //else
                    //{
                    //    спискиЛюдей.Дата_выбытия = null;
                    //}


                    UpdateModel(спискиЛюдей);
                    dataManager.SaveChanges();



                    ViewBag._Message = String.Format("Записись сохранена");

                    return RedirectToAction("Index");


                }
                else
                {
                    return View();
                }

            }
            catch
            {
                return View();
            }

        }

        //
        // GET: /СпискиЛюдей/Delete/5

        public ActionResult Delete(int id)
        {

            return View(dataManager.GetPeaple(id));
        }

        //
        // POST: /СпискиЛюдей/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                dataManager.DeletePeople(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Notphones()
        {
            return View(dataManager.NotPhonePeaple());
        }


        private void SetViewBag()
        {
            ViewBag._Название_SMS = dataManager.SelectListSms();
            ViewBag._Школы = dataManager.SelectListСписокВсехШкол();
            ViewBag._Пол = dataManager.SelectListStringSex();
            ViewBag._Вконтекте = dataManager.SelectListBool();
            ViewBag._Участие_в_выступлениях = dataManager.SelectListBool();

            ViewBag._Район = dataManager.SelectListСписокРайонов();
        }


        private void SetViewBag(Списки_людей спискиЛюдей)
        {
            ViewBag._Название_SMS = dataManager.SelectListSms(спискиЛюдей.Название_SMS.Код);
            ViewBag._Школы = dataManager.SelectListСписокВсехШкол(спискиЛюдей.Название_школ.Код);
            ViewBag._Пол = dataManager.SelectListStringSex(спискиЛюдей.Пол);
            ViewBag._Вконтекте = dataManager.SelectListBool(спискиЛюдей.Вконтекте);
            ViewBag._Участие_в_выступлениях = dataManager.SelectListBool(спискиЛюдей.Участие_в_выступлениях);

            ViewBag._Район = dataManager.SelectListСписокРайонов(спискиЛюдей.Район);
            ViewBag.Alfavit = dataManager.GetAlfavitFromФИО();

        }




        [HttpPost]
        public ActionResult PhoneExist(string Телефон, int? Код)
        {

            //            bool l = Код == null ? dataManager.IsPhoneExists(Телефон) : dataManager.IsPhoneExists(Телефон, Код);

            //if (Код == null)
            //{
            //            return Json(!dataManager.IsPhoneExists(Телефон), JsonRequestBehavior.AllowGet);
            //}
            //else
            //{

            List<string> str = dataManager.IsPhoneExists(Телефон, Код);

            if (str.Count == 0)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                string s1 = "";

                foreach (string s in str)
                {
                    s1 = s + ", " + s1;
                }
                return Json(String.Format("Такой номер телефона уже есть у: {0}. ", s1), JsonRequestBehavior.AllowGet);
            }

            //            }

            //            return Json(str, JsonRequestBehavior.AllowGet);

        }



        [HttpPost]
        public ActionResult EmailExist(string e_mail, int? Код)
        {
            bool l = Код == null ? dataManager.IsEmailExist(e_mail) : dataManager.IsEmailExist(e_mail, Код);

            return Json(!l, JsonRequestBehavior.AllowGet);

            //            return Json(!dataManager.IsPhoneExists(e_mail, Код), JsonRequestBehavior.AllowGet);
        }

 


        [Authorize(Users = "Admin")]
        public ActionResult NotesListAdmin()
        {
            return View("_PartialNotesIndex", dataManager.GetNotes(-13));
        }


        public ActionResult NotesListIndex()
        {
            return PartialView("_PartialNotesIndex", dataManager.GetNotes());
        }


        public ActionResult NotesList(int? id)
        {
            return PartialView("_PartialNotesList", dataManager.GetNotesFromIdPeople(id));
        }

Views/People/Details.cshtml
@using CuatroCaminosMvcApplication
@model CuatroCaminosMvcApplication.Models.Списки_людей

@{
    ViewBag.Title = "Карточка клиента";
}

@if (Model != null)
{
    <h2> Карточка клиента: @Model.ФИО </h2>

    <p>
        @Html.ActionLink("Назад к списку", "Index") | 

        @Html.ActionLink("Создать нового", "Create")
    </p>
    <table>
        <tr>
            <th>
                Дата регистрации <hr/>
                Дата рождения
            </th>
            <th>
                Фамилия<br/>
                Имя<br/>
                Отчество<br/>
            
            </th>
            <th nowrap="nowrap">
                Вконтекте:       <br/>
                Выступления:     <br/>
                Наличие авто:    <br/>
            </th>
            <th>
                От куда узнал
            </th>
            <th>
                Хобби
            </th>
            <th>
                Примечание
            </th>
            <th>
                Выбыл из школы
            </th>
        </tr>

        <tr>
            <td>    
                @Html.DisplayFor(model => model.Дата_регистрации) <hr/>
                @Html.DisplayFor(model => model.Дата_рождения)
            </td>
            <td>
                <b> @Html.DisplayFor(model => model.Фамилия)     <br/>
                    @Html.DisplayFor(model => model.Имя)
                </b>                                                 <br/>
                @Html.DisplayFor(model => model.Отчество)     <br/>  

           
                <br/>
                Телефон: 
                        
               
                @if (!String.IsNullOrEmpty(Model.Телефон))
                {


                    if (HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора 
//                        ||            HttpContext.Current.User.Identity.Name == "9608735873" 
//                        ||            HttpContext.Current.User.Identity.Name == "zlata"
                        )
                    {

                        @:+7 @Html.DisplayFor(model => model.Телефон)

                    }
                    else
                    {
                        @: номер скрыт
                    }

                }
                else
                {
                    @: нет номера
                }

                <br/>
                <br/>                                                             


                Район: @Html.DisplayFor(model => model.Название_района.Название_района1) <br/>
                <br/>
                    @if (HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора)
                    {
                        @:   e - mail:
                        @Html.DisplayFor(model => model.e_mail)
                    }
                    else
                    {
                         @: email скрыт
                    }
                    
                    <br/>
                sms:    @Html.DisplayFor(model => model.Название_SMS.SMS)    <br/>
                <br/>
                Школа:  @Html.DisplayFor(model => model.Название_школ.Школы)
                <br/>
                        
            </td>
            <td>
                Вконтекте: @Html.DisplayFor(model => model.Вконтекте)               <br/>
                Выступл-я: @Html.DisplayFor(model => model.Участие_в_выступлениях)  <br/>
                Авто: @Html.DisplayFor(model => model.Наличие_авто)            <br/>
            </td>
            <td>
                @Html.DisplayFor(model => model.От_куда_узнал_а_)
            </td>
            <td>
                @Html.DisplayFor(model => model.Хобби)
            </td>
            <td>
                @Html.DisplayFor(model => model.Примечание)
            </td>
            <td>
                @Html.DisplayFor(model => model.Выбыл_из_школы)<br/>
                @Html.DisplayFor(model => model.Дата_выбытия)
            </td>
        </tr>

    </table>
    
   <p>
            
            <hr/>

            <div class="display-label">Время внесения записи</div>
            <div class="display-field">
                @Html.DisplayFor(model => model.DateTimeRec)
            </div>

            <div class="display-label">Кто записал запись</div>
            <div class="display-field">
                @ViewBag.LoginRecFio
            </div>
           <br/>
    <hr/>


        </p>
    
    <p>
        @if (HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора)
        {
            @Html.ActionLink("Редактировать", "Edit", new { id = Model.Код })
            @: |
            @Html.ActionLink("Удалить данную запись", "Delete", new { id = Model.Код })
            @: |
        }

    </p>

    <br/>
    <br/>
    <hr/>
    <h2> Вся информация по оплате: @Model.ФИ</h2>
    <p>

        @if (Model.Код != 151)
        {
            @Html.Action("PartialОплата", "Payment")
        }    
    
    </p>

    <br/>
    <hr/>

    
    <h2>Участие в мероприятиях: @Model.ФИ</h2>
    <p>
        @Html.Action("ListActivityDetailsFromPeopleId", "Activity", new { idPeaple = Model.Код })
    </p>
    
        <br/>
    <hr/>

    
    
        <h2> Заметки: @Model.ФИ</h2>

        if (Model.Код != 151)
        {

        <p>    
            @Html.Action("NotesList", "People") 
    
            <br/><br/>
    
            @Html.Action("NotesCreate", "People") 

    
        </p>

        }
        else
        {
        <h4>Произошла ошибка. </h4>
        }

    <br/>
    <hr/>


    

    
    
    
        
    
    
    <p>
        @Html.ActionLink("Назад к списку", "Index") | 

        @Html.ActionLink("Создать нового", "Create")
    </p>

    
}

Views/People/DoNotGo.cshtml
@using CuatroCaminosMvcApplication.Models
@{
    ViewBag.Title = "Список людей, переставших ходить на занятия";
}

<h2>Список людей, переставших ходить на занятия:  @ViewBag.Имя_группы</h2>

<ul>Расчитывается по оплатившим относительно сегодняшнего дня.</ul>
<p>
@Html.ActionLink("Назад к списку", "Index") | 

@if (ViewBag.Имя_группы!= null){

    @Html.ActionLink("Посмотреть оплату за текущий месяц", "Month", "Payment", new { month = DateTime.Now.Month, gruppa = Request.QueryString["Group"]},  new { style = "color: red" }) 
    @:|
}

</p>



<table style="border:none;">
<tr>
<td style="vertical-align: text-top; border:0">

@{
    
    foreach (var название_танцев in ViewBag.Название_танцев as IList<Названия_танцев>)
    {
        
    <br/><strong>
                @Html.ActionLink(название_танцев.Название_танца, "Group", new {Group = название_танцев.Код, Sex = Request.QueryString["Sex"], Pay = Request.QueryString["Pay"]})
        </strong>

                foreach (var day in ViewBag.Days as Dictionary<int, string>)
        {
            <li>
                    @Html.ActionLink(day.Value, "DoNotGo", new { Group = название_танцев.Код, day = day.Key })
            
        </li>
        }
    }
}


</td>
<td  style="vertical-align: text-top; width:80%; border:0">@Html.Partial("_PartialIndex")</td>

</tr>
</table>
<div>
<ul>

</ul>
</div>

Views/People/Group.cshtml
@using CuatroCaminosMvcApplication
@using CuatroCaminosMvcApplication.Models
@model ICollection<CuatroCaminosMvcApplication.Models.Списки_людей>

@{
    ViewBag.Title = "Список людей по группам: " + ViewBag.Имя_группы;
   
}

<h2>Список людей группы: "@ViewBag.Имя_группы"
    
    @if(@ViewBag.Description!=null) {
        <text>(@ViewBag.Description)</text>
    }

</h2> 

            @Html.ActionLink("Назад к списку", "Index")  |
            
            @if (ViewBag.Имя_группы!= null){

            @Html.ActionLink("Посмотреть оплату за текущий месяц", "Month", "Payment", new { month = DateTime.Now.Month, gruppa = Request.QueryString["Group"]},  new { style = "color: red" }) @:|
            }
            
<p>
@{
    foreach (var название_танцев in ViewBag.Название_танцев as IList<Названия_танцев>)
    {
            @Html.ActionLink(название_танцев.Название_танца, "Group", new { Group = название_танцев.Код, Sex = Request.QueryString["Sex"], Pay = Request.QueryString["Pay"] }) @:|  
          
 
    }
}
</p>

@if (HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора)
{

        <p>
        ..... Экспорт телефонов "по оплате": 
                    @Html.ActionLink("Экспорт", "DownloadCSV", new { Group = Request.QueryString["Group"], Sex = Request.QueryString["Sex"], Pay = 1 }) |         
                    @Html.ActionLink("М", "DownloadCSV", new { Group = Request.QueryString["Group"], Sex = 'М', Pay = 1 }) |         
                    @Html.ActionLink("Ж", "DownloadCSV", new { Group = Request.QueryString["Group"], Sex = 'Ж', Pay = 1 }) |

              
         ..... Экспорт телефонов НЕ "по оплате" (кроме выбывших):

                    @Html.ActionLink("Экспорт", "DownloadCSV", new { Group = Request.QueryString["Group"], Sex = Request.QueryString["Sex"] }) |         
                    @Html.ActionLink("М", "DownloadCSV", new { Group = Request.QueryString["Group"], Sex = 'М' }) |         
                    @Html.ActionLink("Ж", "DownloadCSV", new { Group = Request.QueryString["Group"], Sex = 'Ж' }) |

        </p>
}

@Html.Partial("_PartialIndex")

Views/People/Index.cshtml
@using CuatroCaminosMvcApplication

@{
    ViewBag.Title = "Список людей";

    IEnumerable<string> alfavits = ViewBag.Alfavit;

}

<h2>Списки людей</h2>

@ViewBag._Message

<p>
    @Html.ActionLink("Создание карточки клиента", "Create") | 
    @Html.ActionLink("Список по группам", "Group")  |
    
    @Html.ActionLink("Переставшие ходить", "DoNotGo", null, new { style = "color: red" }) |


    @Html.ActionLink("Люди \"Без телефонов\"", "Notphones")  |
    @Html.ActionLink("Печать \"Анкета участника школы\"", null, Url.Content("./Content/Downloads/anketa.pdf"),null, new { target = "blank"}

)  |

@if (HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора)
{

            @Html.ActionLink("Другие школы", "Schools", new { schools = -1 })  @: | 
            @Html.ActionLink("Заметки", "NotesListAdmin") @: | 

    <br/>
}


</p>


Поиск по фамилии: 

    @foreach (string alfavit in alfavits)
    {
        if (!String.IsNullOrEmpty(alfavit))
        {
            @Html.ActionLink(alfavit, "Index", new { alfavit = alfavit }) @:|         
        }

    }

            @Html.ActionLink("ВСЕ", "Index", new { alfavit = "0" }) |         


    <br/>
    <br/>
    
    
@Html.Action("PartialSearchPeople")

    <br/>

@Html.Partial("_PartialIndex")



<p>
    @Html.ActionLink("Создание карточки клиента", "Create") | 
</p>

Views/People/Schools.cshtml
@using CuatroCaminosMvcApplication


@{
    ViewBag.Title = "Список людей";

    ICollection<CuatroCaminosMvcApplication.Models.Название_школ>  названиеШкол = ViewBag.Schools;

    
}

<h2>Список людей школы @ViewBag.School </h2>

@ViewBag._Message



<p>
@*   
    @Html.ActionLink("Создание новой карточки клиента", "Create") | 
    @Html.ActionLink("Люди \"Без телефонов\"", "Notphones")  |
*@

    @Html.ActionLink("Назад", "Index") | 


@if (HttpContext.Current.User.Identity.Name == StaticsVariables.ЛогинАдминистратора)
{
@*           
                 @Html.ActionLink("Salsa Del Amor", "Schools", new {schools = 1}) 
               @: | <br/>
*@
    
    
    foreach (var item in названиеШкол)
    {
        
        
            
        
            @Html.ActionLink(item.Школы, "Schools", new { schools = item.Код }) @:|         
    }


}


</p>

@Html.Partial("_PartialIndex")

<p>
    @Html.ActionLink("Создать нового", "Create") | 
    @Html.ActionLink("Без анкеты", "Notphones")
</p>

Views/People/_PartialNotesIndex.cshtml
@model IEnumerable<CuatroCaminosMvcApplication.Models.Notes>

@if(Model.Any()){
<table>
    <tr>
        <th>
            Дата
        </th>
        <th>
            Имя
        </th>
        <th>
            Текст заметки
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DatePlan)
        </td>
        <td>
            @Html.ActionLink(item.Списки_людей.ФИ, "Details", "People", new { id = item.КодУченика }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
    </tr>
}

</table>
}